// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppFredy.SoalDua.Models
{
    public partial class TbTest
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
    }
}