// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AppFredy.SoalDua.Models;

namespace AppFredy.SoalDua.Data
{
    public partial class dbFredyDevtestContext : DbContext
    {
        public dbFredyDevtestContext()
        {
        }

        public dbFredyDevtestContext(DbContextOptions<dbFredyDevtestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TbTest> TbTest { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TbTest>(entity =>
            {
                entity.ToTable("tbTest");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .HasColumnName("name");

                entity.Property(e => e.Phone)
                    .HasMaxLength(30)
                    .HasColumnName("phone");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}